version: '3'

services:
  app:
    container_name: node-app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 30s node index.js
    build: 
      context: ./app
    volumes:
      - ./app:/src
      - /src/node_modules
    tty: true
    ports:
      - "3000:3000"
    networks:
      - nginx-net
    depends_on:
      - db
  db:
    container_name: db
    build: 
      context: ./mysql
    command: --innodb-use-native-aio=0
    restart: always
    tty: true
    ports:
      - 3306:3306
    volumes: 
      - ./mysql/db:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - nginx-net
  nginx:
    container_name: nginx
    build: 
      context: ./nginx
    networks:
      - nginx-net
    ports:
      - 8080:80
    depends_on:
      - app

networks:
  nginx-net:
    name: nginx-net
    driver: bridge